import {reviewCapacityPolicy} from './review-capacity';
import {packetReadiness,recoveryPlan} from './recovery';
import {Packet} from '../contracts/pipeline';
import {discoveryPriority,reviewProblems,validateResearch} from './policy';
import {draftResearch} from './crm-specialist';
import {procurementDraftProblems} from './procurement';
export function batchReport(rows:{id:string;revision:number;packet_hash:string;packet:unknown;campaign_id?:string}[],labels:{opportunity_id:string;packet_hash:string;labels:unknown}[],campaigns:{id:string;profile:Record<string,unknown>}[]=[]){
 const cases=rows.flatMap(row=>{const parsed=Packet.safeParse(row.packet);if(!parsed.success||parsed.data.mode==='fixture')return [];const p=parsed.data;
 const checked=Boolean(p.packetReview&&p.research&&!reviewProblems(p.packetReview,p.research,p,JSON.stringify(p.research)).length&&p.draft&&p.research&&p.draftReview&&!reviewProblems(p.draftReview,draftResearch(p),p,JSON.stringify(p.draft)).length&&!procurementDraftProblems(p).length);
 return [{id:row.id,campaignId:row.campaign_id??null,allocation:p.reviewAllocation??null,revision:row.revision,source:p.candidate?.source??'unknown',country:p.candidate?.country??'unknown',effectiveSearchCountry:p.candidate?.searchCountry??p.candidate?.country??'unknown',language:p.candidate?.language??'unknown',company:p.research?.company??p.candidate?.procurementNotice?.buyer??null,state:p.state,readiness:packetReadiness(p),recovery:recoveryPlan(p),decision:p.research&&!validateResearch(p.research,p).length?p.research.decision:null,sourceEvidence:p.evidence.filter(e=>e.origin==='original').length,checkedDraft:checked,baselineScore:p.candidate?discoveryPriority(p.candidate):null,humanLabels:labels.find(l=>l.opportunity_id===row.id&&l.packet_hash===row.packet_hash)?.labels??null}];});
 const exploration=cases.filter(c=>c.checkedDraft&&c.decision==='exploration').length,checked=cases.filter(c=>c.checkedDraft).length;
 const cohorts=[...new Set(cases.map(c=>c.campaignId).filter((id):id is string=>id!==null))].map(id=>{
  const members=cases.filter(c=>c.campaignId===id),profile=campaigns.find(c=>c.id===id)?.profile,policy=profile?reviewCapacityPolicy(profile):null;
  const admitted=members.filter(c=>c.allocation?.decision==='admitted'),priority=admitted.filter(c=>c.decision==='priority').length;
  return {campaignId:id,configuredShare:policy?.share??null,policySource:policy?.source??'unavailable',capacity:policy?.capacity??null,explorationLimit:policy?.explorationLimit??null,admitted:admitted.length,priority,exploration:admitted.filter(c=>c.decision==='exploration').length,deferred:members.filter(c=>c.allocation?.decision==='deferred').length,diagnostic:members.filter(c=>c.allocation?.decision==='diagnostic').length,priorityShortfall:policy?Math.max(0,policy.capacity-policy.explorationLimit-priority):null};
 });
 return {allocation:{historical:{exploration,checked,observedShare:checked?exploration/checked:null},cohorts,instruction:'Allocation applies at campaign promotion, never at discovery launch. Diagnostic recovery and prior unallocated drafts are separate; priority shortfalls remain visible.'},generatedAt:new Date().toISOString(),targetDecisions:10,discovered:cases.length,decisions:cases.filter(c=>c.decision).length,checkedDrafts:cases.filter(c=>c.checkedDraft).length,humanRated:cases.filter(c=>c.humanLabels).length,procurementDrafts:cases.filter(c=>c.checkedDraft&&c.state==='procurement_review_ready').length,cases,limitations:['Discovered rows and source failures are not qualified decisions.','Search country/language is not verified buyer geography.','Rule baseline scores are for the same candidate pool; human labels are required to judge usefulness.','Sending, procurement submission and commercial outcomes are outside this POC.']};
}
