'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
const fields=[['serviceRelevance','Service relevance',['useful','unclear','irrelevant']],['factualSupport','Factual support',['supported','needs_correction','unknown']],['offerUsefulness','Offer usefulness',['useful','needs_work','unknown']],['buyerFit','Buyer fit',['appropriate','wrong_buyer','unknown']],['editsRequired','Edits needed',['none','minor','major','no_draft']]] as const;
export function QualityReview({id,revision,packetHash,latest}:{id:string;revision:number;packetHash:string;latest?:{labels:Record<string,unknown>;current:boolean}}){
 const [values,setValues]=useState<Record<string,string>>({}),[note,setNote]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const started=useRef<number|null>(null),inFlight=useRef(false),attempt=useRef<{payload:string;requestKey:string;seconds:number}|null>(null),router=useRouter();
 async function save(){if(inFlight.current)return;inFlight.current=true;setBusy(true);const payload=JSON.stringify({...values,note});const saved=attempt.current?.payload===payload?attempt.current:{payload,requestKey:crypto.randomUUID(),seconds:Math.min(86400,Math.floor((Date.now()-(started.current??Date.now()))/1000))};attempt.current=saved;
  try{const r=await fetch('/api/quality',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,revision,packetHash,requestKey:saved.requestKey,labels:{...values,note,reviewSeconds:saved.seconds}})});if(!r.ok)throw Error(r.status===409?'This record changed. Reload before rating.':'Could not save the quality review.');setMessage('Quality review saved.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Could not save.');}finally{inFlight.current=false;setBusy(false);}}
 return <details onToggle={e=>{if(e.currentTarget.open&&started.current===null)started.current=Date.now();}}><summary>Human quality review · {latest?(latest.current?'recorded':'older version; review again'):'not yet rated'}</summary><p className="footnote">Rate the evidence and useful offer, including deferred or rejected cases. These ratings do not send or approve a message.</p>{latest&&<p className="footnote">Previous note: {String(latest.labels.note??'')}</p>}{fields.map(([key,label,options])=><label key={key}>{label}<select value={values[key]??''} onChange={e=>setValues({...values,[key]:e.target.value})}><option value="">Select a rating</option>{options.map(option=><option key={option} value={option}>{option.replaceAll('_',' ')}</option>)}</select></label>)}<label>Quality review note<textarea value={note} onChange={e=>setNote(e.target.value)} rows={2}/></label><button disabled={busy||!note.trim()||fields.some(([key])=>!values[key])} onClick={save}>Save quality review</button><p aria-live="polite" className="footnote">{message}</p></details>;
}
