'use client';
import {displayDate} from '../src/domain/display-date';
import { useRef,useState } from 'react';
import {useRouter} from 'next/navigation';
import {WebsiteReviewPanel} from './website-review';
import {DiscoveryProvenance,type DiscoveryObservationSummary} from './discovery-provenance';
import type { Packet } from '../src/contracts/pipeline';
export function ReviewCard({id,revision,packet:p,crmChecked,websiteChecked,discoveryObservations=[]}:{id:string;revision:number;packet:Packet;crmChecked:boolean;websiteChecked:boolean;discoveryObservations?:DiscoveryObservationSummary[]}) {
 const [subject,setSubject]=useState(p.draft?.subject??''),[body,setBody]=useState(p.draft?.body??''),[note,setNote]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const requestAttempt=useRef<{key:string;body:string}|null>(null),inFlight=useRef(false),router=useRouter();
 const dirty=subject!==(p.draft?.subject??'')||body!==(p.draft?.body??'');
 async function review(action:string){
  if(inFlight.current)return;inFlight.current=true;setBusy(true);setMessage('');const command={id,revision,action,note,draft:p.draft?{...p.draft,subject,body}:null};
  const fingerprint=JSON.stringify(command),key=requestAttempt.current?.body===fingerprint?requestAttempt.current.key:crypto.randomUUID();requestAttempt.current={key,body:fingerprint};
  try{const r=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...command,requestKey:key})});const result=await r.json();if(!r.ok){if(r.status<500)requestAttempt.current=null;throw new Error(result.error??'Review failed');}setMessage('Saved.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Could not save.');}finally{inFlight.current=false;setBusy(false);}
 }
 const r=p.research;
 return <article className="card"><div className="card-heading"><div><p className="eyebrow">{r?.service??'NEW DISCOVERY'} · {r?.decision??'RESEARCH PENDING'}</p><h2>{r?.company??p.candidate?.title??'Opportunity'}</h2><p className="muted">{r?.accountHost??p.candidate?.url}</p></div><span className={`badge ${p.mode==='fixture'?'fixture':''}`}>{p.mode==='fixture'?'Verification fixture · not a prospect':p.state.replaceAll('_',' ')}</span></div>
 <div className="card-grid"><section><h3>Why this company, why now</h3><p>{r?.whyNow??'Original evidence has not been researched yet.'}</p>{r&&<><h3>The useful offer</h3><p>{r.offer}</p><h3>Buyer & relationship</h3><p>{p.contact?.name??r.buyerRole} · {p.contact?.email??'Contact pending'}</p><p className="muted">{p.contact?.reason??'Contact resolution follows evidence review.'} Relationship history: {p.relationship}.</p></>}
 {Boolean(p.contact?.candidates?.length)&&<details><summary>Buyer candidates · {p.contact!.candidates!.length}</summary>{p.contact!.candidates!.map(c=><div key={c.providerId}><p><strong>{c.displayName}</strong> · {c.role} · {c.company}</p><p className="footnote">{c.reason} {c.refreshedAt?`Provider refreshed ${displayDate(c.refreshedAt)}.`:'Provider freshness unknown.'}</p></div>)}</details>}
 <DiscoveryProvenance packet={p} observations={discoveryObservations}/>
 <h3>Evidence trail <span className="count">{p.evidence.length}</span></h3>{p.evidence.map(e=><details key={e.id}><summary>{e.title}</summary><a href={e.finalUrl} target="_blank" rel="noreferrer">View original source ↗</a><p className="footnote">Retrieved {displayDate(e.retrievedAt)} · {e.status} · {e.origin}</p><blockquote>{e.text.slice(0,3000)}</blockquote></details>)}
 {r?.claims.map(c=><p className="claim" key={c.id}><span>{c.kind}</span>{c.text}</p>)}
 <h3>Uncertainties & contrary evidence</h3><ul>{[...(r?.uncertainties??[]),...(r?.contrary??[])].map((n,i)=><li key={i}>{n}</li>)}</ul>
 {p.notes.length>0&&<details><summary>Processing history · {p.notes.length}</summary><p className="footnote">Earlier checks and recovery notes. Current review results are shown with the draft and specialist analysis.</p><ul>{p.notes.map((n,i)=><li key={i}>{n}</li>)}</ul></details>}
 {p.crmSupplement&&<><h3>CRM / operations analysis</h3><p className="footnote">Evidence review: {crmChecked?'checked':'pending or repair needed'} · Suggested scope requires buyer confirmation.</p>{!crmChecked&&<ul>{p.crmSupplement.review?.issues.map((issue,i)=><li key={i}>{issue}</li>)}</ul>}{p.crmSupplement.analysis.findings.length===0&&<p>No supported CRM findings in the available evidence.</p>}{p.crmSupplement.analysis.findings.map(f=><details key={f.id}><summary>{f.observation}</summary><blockquote>{f.quote}</blockquote>{p.evidence.find(e=>e.id===f.evidenceId)&&<a href={p.evidence.find(e=>e.id===f.evidenceId)!.finalUrl} target="_blank" rel="noreferrer">Supporting source ↗</a>}<p><strong>Hypothesis:</strong> {f.hypothesis}</p><p><strong>Validate with the buyer:</strong> {f.question}</p><p><strong>Possible deliverable:</strong> {f.deliverable}</p></details>)}<ul>{p.crmSupplement.analysis.limitations.map((item,i)=><li key={i}>{item}</li>)}</ul></>}
 <WebsiteReviewPanel id={id} packet={p} checked={websiteChecked}/>
 {p.specialistFindings.length>0&&<><h3>Specialist observations</h3>{p.specialistFindings.map((f,i)=><p key={i}><strong>{f.profile.toUpperCase()} · {f.metric}</strong><br/>{f.observation}<br/><span className="muted">Hypothesis: {f.hypothesis}</span></p>)}</>}</section>
 <section className="draft"><div className="draft-top"><h3>Draft for review</h3><span>VERSION {revision}</span></div>{p.draft?<><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Message<textarea value={body} onChange={e=>setBody(e.target.value)} rows={12}/></label><p className="footnote">Packet review: {p.packetReview?.acceptable?'checked':'pending'} · Draft review: {!dirty&&p.draftReview?.acceptable?'checked':'pending or repair needed'}</p></>:<p className="muted">The checked draft will appear after research and evidence review.</p>}
 <label>Review note or specific research question<textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="What would change your decision?"/></label><div className="actions"><button disabled={busy||!note.trim()||!p.draft||!dirty||!subject.trim()||!body.trim()} onClick={()=>review('edit')}>Save edit & check</button><button disabled={busy||!note.trim()||!p.draft||dirty} onClick={()=>review('recheck')}>Recheck draft</button><button disabled={busy||!note.trim()||dirty} onClick={()=>review('research')}>Request research</button><button disabled={busy||!note.trim()||dirty} onClick={()=>review('defer')}>Defer</button><button disabled={busy||!note.trim()||dirty} onClick={()=>review('reject')}>Reject</button></div><button type="button" className="primary" onClick={()=>setMessage("Email sending is not available yet. This POC ends at a reviewed draft; no email has been sent.")}>Send email</button><p aria-live="polite" className="footnote">{message||(dirty?'Unsaved edits. Save the edit and request a claim check before another review action.':p.state==='review_required'?'Fresh claim check required. The local worker runs queued checks when campaign and budget limits allow.':'Edits and rechecks preserve your wording; unsupported claims return for your correction.')}</p></section></div></article>;
}
