'use client';
import { useState } from 'react';
import type { Packet } from '../src/contracts/pipeline';
export function ReviewCard({id,revision,packet:p}:{id:string;revision:number;packet:Packet}) {
 const [subject,setSubject]=useState(p.draft?.subject??''),[body,setBody]=useState(p.draft?.body??''),[note,setNote]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [requestAttempt,setRequestAttempt]=useState<{key:string;body:string}|null>(null);
 async function review(action:string){
  setBusy(true);setMessage('');const command={id,revision,action,note,draft:p.draft?{...p.draft,subject,body}:null};
  const fingerprint=JSON.stringify(command),key=requestAttempt?.body===fingerprint?requestAttempt.key:crypto.randomUUID();setRequestAttempt({key,body:fingerprint});
  try{const r=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...command,requestKey:key})});const result=await r.json();if(!r.ok){if(r.status<500)setRequestAttempt(null);throw new Error(result.error??'Review failed');}setMessage('Saved.');window.location.reload();}catch(e){setMessage(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}
 }
 const r=p.research;
 return <article className="card"><div className="card-heading"><div><p className="eyebrow">{r?.service??'NEW DISCOVERY'} · {r?.decision??'RESEARCH PENDING'}</p><h2>{r?.company??p.candidate?.title??'Opportunity'}</h2><p className="muted">{r?.accountHost??p.candidate?.url}</p></div><span className={`badge ${p.mode==='fixture'?'fixture':''}`}>{p.mode==='fixture'?'Fixture · not live':p.state.replaceAll('_',' ')}</span></div>
 <div className="card-grid"><section><h3>Why this company, why now</h3><p>{r?.whyNow??'Original evidence has not been researched yet.'}</p>{r&&<><h3>The useful offer</h3><p>{r.offer}</p><h3>Buyer & relationship</h3><p>{p.contact?.name??r.buyerRole} · {p.contact?.email??'Contact pending'}</p><p className="muted">{p.contact?.reason??'Contact resolution follows evidence review.'} Relationship history: {p.relationship}.</p></>}
 {Boolean(p.contact?.candidates?.length)&&<details><summary>Buyer candidates · {p.contact!.candidates!.length}</summary>{p.contact!.candidates!.map(c=><div key={c.providerId}><p><strong>{c.displayName}</strong> · {c.role} · {c.company}</p><p className="footnote">{c.reason} {c.refreshedAt?`Provider refreshed ${new Date(c.refreshedAt).toLocaleDateString()}.`:'Provider freshness unknown.'}</p></div>)}</details>}
 <h3>Evidence trail <span className="count">{p.evidence.length}</span></h3>{p.evidence.map(e=><details key={e.id}><summary>{e.title}</summary><a href={e.finalUrl} target="_blank" rel="noreferrer">View original source ↗</a><p className="footnote">Retrieved {new Date(e.retrievedAt).toLocaleDateString()} · {e.status} · {e.origin}</p><blockquote>{e.text.slice(0,3000)}</blockquote></details>)}
 {r?.claims.map(c=><p className="claim" key={c.id}><span>{c.kind}</span>{c.text}</p>)}
 <h3>Uncertainties & contrary evidence</h3><ul>{[...(r?.uncertainties??[]),...(r?.contrary??[]),...p.notes.map(n=>p.packetReview?.acceptable&&/^(Unsupported quotation|Unresolved source attribution|Unverified company identity)/.test(n)?`Earlier check, resolved: ${n}`:n)].map((n,i)=><li key={i}>{n}</li>)}</ul>
 {p.specialistFindings.length>0&&<><h3>Specialist observations</h3>{p.specialistFindings.map((f,i)=><p key={i}><strong>{f.profile.toUpperCase()} · {f.metric}</strong><br/>{f.observation}<br/><span className="muted">Hypothesis: {f.hypothesis}</span></p>)}</>}</section>
 <section className="draft"><div className="draft-top"><h3>Draft for review</h3><span>VERSION {revision}</span></div>{p.draft?<><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Message<textarea value={body} onChange={e=>setBody(e.target.value)} rows={12}/></label><p className="footnote">Packet review: {p.packetReview?.acceptable?'checked':'pending'} · Draft review: {p.draftReview?.acceptable?'checked':'pending or repair needed'}</p></>:<p className="muted">The checked draft will appear after research and evidence review.</p>}
 <label>Review note or specific research question<textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="What would change your decision?"/></label><div className="actions"><button disabled={busy||!note.trim()||!p.draft} onClick={()=>review('edit')}>Save edit</button><button disabled={busy||!note.trim()} onClick={()=>review('research')}>Request research</button><button disabled={busy||!note.trim()} onClick={()=>review('defer')}>Defer</button><button disabled={busy||!note.trim()} onClick={()=>review('reject')}>Reject</button></div><button className="primary" disabled>Approval unavailable · sending disabled</button><p aria-live="polite" className="footnote">{message||'Edits create a new version and require a fresh claim review.'}</p></section></div></article>;
}
