'use client';
import {intentIcp} from '../src/domain/intent-icp';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {workflowSummary,stageNames,failureMessage,type WorkflowStatus} from '../src/domain/workflow-status';
export function WorkflowPanel({organizationId}:{organizationId:string}){
 const [status,setStatus]=useState<WorkflowStatus|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const request=useRef<string|null>(null),flight=useRef(false),prior=useRef<string|null>(null),router=useRouter();
 useEffect(()=>{let disposed=false;const controller=new AbortController();async function poll(){try{const r=await fetch('/api/workflow',{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error('Workflow status is unavailable.');const data:WorkflowStatus=await r.json();if(disposed)return;setStatus(data);setError('');const version=JSON.stringify([data.run?.id,data.jobs.map(j=>[j.id,j.status]),data.opportunities.map(o=>[o.id,o.state])]);if(prior.current&&prior.current!==version)router.refresh();prior.current=version;}catch{if(!disposed)setError('Workflow status is unavailable. The last displayed status may be stale.');}}
 void poll();const timer=setInterval(()=>{if(document.visibilityState==='visible')void poll();},6000);return()=>{disposed=true;controller.abort();clearInterval(timer);};},[router]);
 async function start(){if(flight.current)return;flight.current=true;setBusy(true);setMessage('');request.current??=crypto.randomUUID();try{const r=await fetch('/api/workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId,requestKey:request.current})});const data=await r.json();if(!r.ok)throw Error(data.error??'Could not start workflow');request.current=null;setMessage(data.created?'Queued a bounded batch. Progress updates automatically.':'A run already exists; showing its progress.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Request outcome unknown. Retry safely with the same request.');}finally{flight.current=false;setBusy(false);}}
 const summary=status?workflowSummary(status):null;
 return <section className="workflow card" aria-label="Workflow"><div className="title-row"><div><h2>Run workflow</h2><p className="muted">Explorium/Bombora intent discovery · ends at checked drafts.</p></div><button onClick={start} disabled={busy||Boolean(summary?.active)||!status||Boolean(error)||status?.setup?.ready!==true}>{busy?'Queuing…':'Run workflow'}</button></div><p className="footnote">500–10,000 employees · India, US, UK, Australia, New Zealand, UAE/Dubai and Singapore. The cumulative $2 cap includes unresolved reservations.</p><details><summary>Target ICP and intent topics</summary><p>Industries: {intentIcp.industries.join(', ')}.</p><p>Active pilot: Pardot. Apollo is used for contacts.</p><p>Requested intent topics: {intentIcp.intentTopics.join(', ')}.</p><p>Decision-maker titles: {intentIcp.buyerTitles.join(', ')}.</p></details>{status?.setup&&!status.setup.ready&&<p role="status"><strong>Discovery setup required.</strong> {status.setup.reason}</p>}<p aria-live="polite"><strong>{summary?.phase??'Loading status…'}</strong> · {status?.worker.online?'Laptop worker online':'Laptop worker offline'}{summary?.active&&!status?.worker.online?' — keep the laptop awake and start the local worker to continue.':''}</p>{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="error">{error}</p>}
 {status?.run&&summary&&<><p>{status.companyCount??0} companies identified · {status.opportunities.length} discovered records · {summary.finished} steps completed · {summary.queued.length} queued · {summary.failed.length} blocked or failed</p>{summary.running.map(j=><p key={j.id}><strong>{stageNames[j.stage]??j.stage}</strong> — {status.opportunities.find(o=>o.id===j.opportunity_id)?.name??'Discovery batch'}</p>)}<details><summary>Progress and issues</summary>{status.jobs.map(j=><div className="workflow-step" key={j.id}><strong>{stageNames[j.stage]??j.stage}</strong><span>{j.status}</span><p>{status.opportunities.find(o=>o.id===j.opportunity_id)?.name??'Discovery search'}{j.error?` · ${failureMessage(j.error)}`:''}</p></div>)}{status.opportunities.map(o=><p key={o.id}>{o.name} · {o.state.replaceAll('_',' ')}</p>)}</details><p className="footnote">Completed processing can produce a useful draft, an unresolved source or a rejection. Human quality ratings remain separate.</p></>}
 </section>;
}
