import {readFile,writeFile} from 'node:fs/promises';
import {serviceClient} from '../src/persistence/client';
import {batchReport} from '../src/domain/batch-report';
import {money,usd} from '../src/usage/money';
import {hash,discoveryPriority} from '../src/domain/policy';
const c=serviceClient(),project=JSON.parse(await readFile('.local/project.json','utf8')),path='.local/completion-run.json',mode=process.argv[2];
if(mode==='prepare'){
 try{await readFile(path);throw Error('existing_completion_run_preserved');}catch(e){if(!(e instanceof Error&&'code' in e&&e.code==='ENOENT'))throw e;}
 const {data:budget,error}=await c.from('budget').select('*').eq('id',1).single();if(error||Number(budget.limit_usd)!==2||!budget.live_enabled)throw Error('unchanged_two_dollar_cap_required');
 const until=new Date(Date.now()+3600000).toISOString();
 // Renew only the run window for already verified product endpoints. Cumulative dollars/units stay unchanged.
 for(const provider of ['openai','brave','apollo']){const {data:l,error}=await c.from('provider_limits').select('*').eq('provider',provider).single();const prior=await c.from('provider_operations').select('id').eq('provider',provider).eq('state','succeeded').not('actual_usd','is',null).limit(1);if(error||prior.error||!prior.data?.length||!l.verified_at)throw Error('saved_endpoint_verification_required');const {error:updated}=await c.from('provider_limits').update({expires_at:until,probe_enabled:true}).eq('provider',provider);if(updated)throw Error('execution_window_update_failed');}
 const {error:enabled}=await c.from('provider_limits').update({free_units:1,verified_at:new Date().toISOString(),expires_at:until,probe_enabled:true,evidence:JSON.stringify({kind:'public_open_data',source:'https://www.gov.uk/government/publications/open-contracting',requestCeiling:1,reason:'One bounded automatic procurement feed read; no subscription or credentials.'})}).eq('provider','contracts_finder');if(enabled)throw Error('public_source_enable_failed');
 const groups=[{source:'contracts_finder',region:'Europe',country:'GB',language:'en',query:'CRM'},...([{region:'US',country:'US'},{region:'Europe',country:'GB'},{region:'Australia',country:'AU'},{region:'Asia',country:'SG'}].map(g=>({...g,source:'brave',language:'en',query:'"HubSpot" ("implementation" OR "integration" OR "migration") (site:jobs.lever.co OR site:job-boards.greenhouse.io OR site:jobs.ashbyhq.com) -template -guide'})))];
 const profile={version:5,name:'HubSpot POC completion · bounded regional and procurement',groups,maxResearch:1,groupIndex:0,sendingEnabled:false};
 const {data:campaign,error:created}=await c.from('campaigns').insert({organization_id:project.organizationId,name:profile.name,version:profile.version,profile,paused:false}).select('id').single();if(created)throw Error('completion_campaign_create_failed');
 await writeFile(path,JSON.stringify({campaignId:campaign.id,organizationId:project.organizationId,groups:groups.length,expiresAt:until,profileHash:hash(profile)}),{mode:0o600,flag:'wx'});console.log(JSON.stringify({prepared:true,groups:groups.length,maxPublicFeedReads:1,maxRegionalSearches:4,capUnchanged:2}));
}else if(mode==='next'){
 const run=JSON.parse(await readFile(path,'utf8'));const {data:campaign,error}=await c.from('campaigns').select('discovery_cursor').eq('id',run.campaignId).single();if(error)throw Error('campaign_read_failed');if(campaign.discovery_cursor>=run.groups){console.log('All bounded groups dispatched.');process.exit(0);}const result=await c.rpc('queue_discovery',{p_campaign:run.campaignId});if(result.error)throw Error(result.error.message);console.log(JSON.stringify(result.data));
}else if(mode==='advance'){
 const run=JSON.parse(await readFile(path,'utf8'));const [rows,jobs]=await Promise.all([c.from('opportunities').select('id,campaign_id,revision,packet').eq('campaign_id',run.campaignId).eq('state','discovered'),c.from('jobs').select('opportunity_id').eq('campaign_id',run.campaignId).eq('stage','S04')]);if(rows.error||jobs.error)throw Error('saved_candidates_unavailable');if(jobs.data.length>=10){console.log('Ten source attempts reached.');process.exit(0);}const attempted=new Set(jobs.data.map(j=>j.opportunity_id));const row=rows.data.filter(r=>!attempted.has(r.id)&&r.packet.candidate&&!r.packet.candidate.procurementNotice).sort((a,b)=>discoveryPriority(b.packet.candidate)-discoveryPriority(a.packet.candidate))[0];if(!row){console.log('No unattempted saved candidate.');process.exit(0);}
 const {error}=await c.from('jobs').upsert({organization_id:run.organizationId,campaign_id:row.campaign_id,opportunity_id:row.id,business_key:`${row.id}:S04:${row.revision}`,stage:'S04',input_hash:hash(row.packet),input_version:row.revision,schema_version:'1',prompt_version:'10',payload:row.packet},{onConflict:'organization_id,business_key',ignoreDuplicates:true});if(error)throw Error('enqueue_failed');console.log(JSON.stringify({queued:true,source:row.packet.candidate.source}));
}else if(mode==='report'){
 const [rows,labels,operations,jobs,coverage]=await Promise.all([c.from('opportunities').select('id,revision,packet_hash,packet').eq('organization_id',project.organizationId),c.from('quality_labels').select('opportunity_id,packet_hash,labels').eq('organization_id',project.organizationId).order('created_at',{ascending:false}),c.from('provider_operations').select('provider,opportunity_id,campaign_id,usage,actual_usd,reserved_usd,state,units').eq('organization_id',project.organizationId),c.from('jobs').select('id,stage,status,error').eq('organization_id',project.organizationId),c.from('stage_runs').select('output').eq('organization_id',project.organizationId)]);
 if(rows.error||labels.error||operations.error||jobs.error||coverage.error)throw Error('report_read_failed');const report={...batchReport(rows.data,labels.data),operations:operations.data,jobs:jobs.data,coverage:coverage.data.map(x=>x.output).filter(o=>o.group).map(o=>({group:o.group,candidates:o.candidates?.length??null}))};await writeFile('.local/poc-completion-report.json',JSON.stringify(report,null,2),{mode:0o600});console.log(JSON.stringify({discovered:report.discovered,decisions:report.decisions,checkedDrafts:report.checkedDrafts,humanRated:report.humanRated,procurementDrafts:report.procurementDrafts,activeJobs:jobs.data.filter(j=>['queued','running'].includes(j.status)).length,recorded:usd(operations.data.reduce((n,o)=>n+money(String(o.actual_usd??0)),0n)),held:usd(operations.data.reduce((n,o)=>n+(o.actual_usd===null?money(String(o.reserved_usd)):0n),0n))}));
}else throw Error('use_prepare_next_advance_or_report');
